# -*- coding: utf-8 -*-
"""M_Letter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fV8KVfCck1_gC0Mh1qTb7nbMohy-pf4Y
"""

import numpy as np
from PIL import Image

class lang_letter():
     lang_dict={}
     def __init__(self,lang_name,lang_location):
         self.lang_name=lang_name
         self.lang_location=lang_location
         self.image=Image.open(self.lang_location)
         self.lang_letter_array=np.asarray(self.image)
         lang_letter.lang_dict.update({self.lang_name:self.lang_letter_array})

M_lang_letters=lang_letter("mom","/content/drive/MyDrive/e0084d1c-eeb0-45f9-9cf1-a7733b252cb9.png")

M_lang_letters.lang_dict

M_lang_letters=lang_letter("Maaka","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maaka.png")

M_lang_letters.lang_dict



M_lang_letters=lang_letter("Maan","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maan.png")

M_lang_letters=lang_letter("Maasai","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maasai.png")

M_lang_letters=lang_letter("Macedonian","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Macedonian.png")

M_lang_letters=lang_letter("Macushi","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Macushi.png")

M_lang_letters=lang_letter("Madura","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Madura.png")

M_lang_letters=lang_letter("Magahi","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Magahi.png")

M_lang_letters=lang_letter("Magar, Eastern","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Magar, Eastern.png")

M_lang_letters=lang_letter("Magi","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Magi.png")

M_lang_letters=lang_letter("Maguindanaon","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maguindanaon.png")

M_lang_letters=lang_letter("Mahou","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mahou.png")

M_lang_letters=lang_letter("Maidu, Northwest","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maidu, Northwest.png")

M_lang_letters=lang_letter("Maithili","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maithili.png")

M_lang_letters=lang_letter("Maiwa","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maiwa.png")

M_lang_letters=lang_letter("Majhi","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Majhi.png")

M_lang_letters=lang_letter("Maka","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maka.png")

M_lang_letters=lang_letter("Makah","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Makah.png")

M_lang_letters=lang_letter("Makalero","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Makalero.png")

M_lang_letters=lang_letter("Makasar","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Makasar.png")

M_lang_letters=lang_letter("Makhuwa","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Makhuwa.png")

M_lang_letters=lang_letter("Makonde","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Makonde.png")

M_lang_letters=lang_letter("Makuva","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Makuva.png")

M_lang_letters=lang_letter("Malagasy","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Malagasy.png")

M_lang_letters=lang_letter("Malango","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Malango.png")

M_lang_letters=lang_letter("Malay","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Malay.png")

M_lang_letters=lang_letter("Maldivian","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maldivian.png")

M_lang_letters=lang_letter("Malila","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Malila.png")

M_lang_letters=lang_letter("Maltese","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maltese.png")

M_lang_letters=lang_letter("Mam","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mam.png")

M_lang_letters=lang_letter("Mamaindê","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mamaindê.png")

M_lang_letters=lang_letter("Mampruli","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mampruli.png")

M_lang_letters=lang_letter("Manchu","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Manchu.png")

M_lang_letters=lang_letter("Mandaic","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mandaic.png")

M_lang_letters=lang_letter("Mandan","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mandan.png")

M_lang_letters=lang_letter("Mandar","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mandar.png")

M_lang_letters=lang_letter("Mandeali","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mandeali.png")

M_lang_letters=lang_letter("Mandinka","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mandinka.png")

M_lang_letters=lang_letter("Mangareva","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mangareva.png")

M_lang_letters=lang_letter("Manggarai","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Manggarai.png")

M_lang_letters=lang_letter("Manide","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Manide.png")

M_lang_letters=lang_letter("Maninkakan, Eastern","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maninkakan, Eastern.png")

M_lang_letters=lang_letter("Mankanya","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mankanya.png")

M_lang_letters=lang_letter("Mannan","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mannan.png")

M_lang_letters=lang_letter("Manobo, Obo","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Manobo, Obo.png")

M_lang_letters=lang_letter("Mansi","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mansi.png")

M_lang_letters=lang_letter("Manx","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Manx.png")

M_lang_letters=lang_letter("Manya","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Manya.png")

M_lang_letters=lang_letter("Maori","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maori.png")

M_lang_letters=lang_letter("Maranao","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maranao.png")

M_lang_letters=lang_letter("Marathi","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Marathi.png")

M_lang_letters=lang_letter("Marba","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Marba.png")

M_lang_letters=lang_letter("Mari","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mari.png")

M_lang_letters=lang_letter("Marma","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Marma.png")

M_lang_letters=lang_letter("Marquesan, South","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Marquesan, South.png")

M_lang_letters=lang_letter("Marshallese","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Marshallese.png")

M_lang_letters=lang_letter("Martu Wangka","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Martu Wangka.png")

M_lang_letters=lang_letter("Marwari","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Marwari.png")

M_lang_letters=lang_letter("Masaaba","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Masaaba.png")

M_lang_letters=lang_letter("Masbatenyo","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Masbatenyo.png")

M_lang_letters=lang_letter("Mashi","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mashi.png")

M_lang_letters=lang_letter("Maskelynes","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maskelynes.png")

M_lang_letters=lang_letter("Mato","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mato.png")

M_lang_letters=lang_letter("Maung","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maung.png")

M_lang_letters=lang_letter("Mawa","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mawa.png")

M_lang_letters=lang_letter("Maya, Mopán","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maya, Mopán.png")

M_lang_letters=lang_letter("Maya, Yucatec","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Maya, Yucatec.png")

M_lang_letters=lang_letter("Mayo","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mayo.png")

M_lang_letters=lang_letter("Mazahua, Central","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mazahua, Central.png")

M_lang_letters=lang_letter("Mazatec, Ayautla","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mazatec, Ayautla.png")

M_lang_letters=lang_letter("Mazatec, Chiquihuitlán","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mazatec, Chiquihuitlán.gif")

M_lang_letters=lang_letter("Ma’di","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Ma’di.png")

M_lang_letters=lang_letter("Mbala","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mbala.png")

M_lang_letters=lang_letter("Mbato","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mbato.gif")

M_lang_letters=lang_letter("Mbesa","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mbesa.png")

M_lang_letters=lang_letter("Mbudum","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Mbudum.gif")

M_lang_letters=lang_letter("Ye'kuana (Maquiritari)","/content/drive/MyDrive/Colab Notebooks/language project/mpic/Ye'kuana (Maquiritari).png")

M_lang_letters=lang_letter("Maa","/content/drive/MyDrive/Colab Notebooks/language project/mpic/maa.png")

M_lang_letters=lang_letter("Malayalam_ar","/content/drive/MyDrive/Colab Notebooks/language project/mpic/malayalam_ar.gif")

M_lang_letters=lang_letter("mali","/content/drive/MyDrive/Colab Notebooks/language project/mpic/mali.gif")

M_lang_letters=lang_letter("maricopa","/content/drive/MyDrive/Colab Notebooks/language project/mpic/maricopa.gif")

M_lang_letters=lang_letter("mamanwa","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mamanwa.gif")

M_lang_letters=lang_letter("mbula","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mbula.gif")

M_lang_letters=lang_letter("mbum","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mbum.gif")

M_lang_letters=lang_letter("mbaund","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mbunda.gif")

M_lang_letters=lang_letter("meankieli","/content/drive/MyDrive/Colab Notebooks/language project/M letter/meankieli.gif")

M_lang_letters=lang_letter("meitei","/content/drive/MyDrive/Colab Notebooks/language project/M letter/meitei.png")

M_lang_letters=lang_letter("melanau central","/content/drive/MyDrive/Colab Notebooks/language project/M letter/melanau central.gif")

M_lang_letters=lang_letter("mele-fila","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mele-fila.gif")

M_lang_letters=lang_letter("mende","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mende.gif")

M_lang_letters=lang_letter("menik","/content/drive/MyDrive/Colab Notebooks/language project/M letter/menik.gif")

M_lang_letters=lang_letter("menominee","/content/drive/MyDrive/Colab Notebooks/language project/M letter/menominee.gif")

M_lang_letters=lang_letter("mentawai","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mentawai.gif")

M_lang_letters=lang_letter("meriam mir","/content/drive/MyDrive/Colab Notebooks/language project/M letter/meriam mir.gif")

M_lang_letters=lang_letter("merwari","/content/drive/MyDrive/Colab Notebooks/language project/M letter/merwari.gif")

M_lang_letters=lang_letter("meskwaki","/content/drive/MyDrive/Colab Notebooks/language project/M letter/meskwaki.gif")

M_lang_letters=lang_letter("mewari","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mewari.gif")

M_lang_letters=lang_letter("miami","/content/drive/MyDrive/Colab Notebooks/language project/M letter/miami.gif")

M_lang_letters=lang_letter("michif","/content/drive/MyDrive/Colab Notebooks/language project/M letter/michif.gif")

M_lang_letters=lang_letter("migaama","/content/drive/MyDrive/Colab Notebooks/language project/M letter/migaama.gif")

M_lang_letters=lang_letter("miji","/content/drive/MyDrive/Colab Notebooks/language project/M letter/miji.gif")

M_lang_letters=lang_letter("mikasuki","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mikasuki.gif")

M_lang_letters=lang_letter("mikmaq","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mikmaq.gif")

M_lang_letters=lang_letter("minangkabau","/content/drive/MyDrive/Colab Notebooks/language project/M letter/minangkabau.gif")

M_lang_letters=lang_letter("mingrelian","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mingrelian.gif")

M_lang_letters=lang_letter("mirandese","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mirandese.gif")

M_lang_letters=lang_letter("miriwoong","/content/drive/MyDrive/Colab Notebooks/language project/M letter/miriwoong.gif")

M_lang_letters=lang_letter("miskito","/content/drive/MyDrive/Colab Notebooks/language project/M letter/miskito.gif")

M_lang_letters=lang_letter("mixe, isthumus","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mixe, isthumus.gif")

M_lang_letters=lang_letter("mixe,tlahuitoltepec","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mixe,tlahuitoltepec.gif")

M_lang_letters=lang_letter("mixe,totontepec","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mixe,totontepec.gif")

M_lang_letters=lang_letter("mixtec, coatzospan","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mixtec, coatzospan.gif")

M_lang_letters=lang_letter("mixtec,Chayuco","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mixtec,Chayuco.gif")

M_lang_letters=lang_letter("miyako","/content/drive/MyDrive/Colab Notebooks/language project/M letter/miyako.gif")

M_lang_letters=lang_letter("mizo","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mizo.gif")

M_lang_letters=lang_letter("moba","/content/drive/MyDrive/Colab Notebooks/language project/M letter/moba.gif")

M_lang_letters=lang_letter("mocheno","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mocheno.gif")

M_lang_letters=lang_letter("mocho","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mocho.gif")

M_lang_letters=lang_letter("mogholi","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mogholi.gif")

M_lang_letters=lang_letter("mohawk","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mohawk.gif")

M_lang_letters=lang_letter("mokilese","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mokilese.gif")

M_lang_letters=lang_letter("moksha","/content/drive/MyDrive/Colab Notebooks/language project/M letter/moksha.gif")

M_lang_letters=lang_letter("molbog","/content/drive/MyDrive/Colab Notebooks/language project/M letter/molbog.gif")

M_lang_letters=lang_letter("moloko","/content/drive/MyDrive/Colab Notebooks/language project/M letter/moloko.gif")

M_lang_letters=lang_letter("mon","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mon.gif")

M_lang_letters=lang_letter("mongolian","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mongolian.gif")

M_lang_letters=lang_letter("mongondow","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mongondow.gif")

M_lang_letters=lang_letter("mono","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mono.gif")

M_lang_letters=lang_letter("montenegrin","/content/drive/MyDrive/Colab Notebooks/language project/M letter/montenegrin.gif")

M_lang_letters=lang_letter("moriatas","/content/drive/MyDrive/Colab Notebooks/language project/M letter/moriatas.gif")

M_lang_letters=lang_letter("moriori","/content/drive/MyDrive/Colab Notebooks/language project/M letter/moriori.gif")

M_lang_letters=lang_letter("morokodo","/content/drive/MyDrive/Colab Notebooks/language project/M letter/morokodo.gif")

M_lang_letters=lang_letter("moronene","/content/drive/MyDrive/Colab Notebooks/language project/M letter/moronene.gif")

M_lang_letters=lang_letter("mortlockese","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mortlockese.gif")

M_lang_letters=lang_letter("moru","/content/drive/MyDrive/Colab Notebooks/language project/M letter/moru.gif")

M_lang_letters=lang_letter("motu,hiri","/content/drive/MyDrive/Colab Notebooks/language project/M letter/motu,hiri.gif")

M_lang_letters=lang_letter("motu","/content/drive/MyDrive/Colab Notebooks/language project/M letter/motu.gif")

M_lang_letters=lang_letter("mualang","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mualang.gif")

M_lang_letters=lang_letter("muna","/content/drive/MyDrive/Colab Notebooks/language project/M letter/muna.gif")

M_lang_letters=lang_letter("mundang","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mundang.gif")

M_lang_letters=lang_letter("mundari","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mundari.gif")

M_lang_letters=lang_letter("munji","/content/drive/MyDrive/Colab Notebooks/language project/M letter/munji.gif")

M_lang_letters=lang_letter("muong","/content/drive/MyDrive/Colab Notebooks/language project/M letter/muong.gif")

M_lang_letters=lang_letter("murrinh-patha","/content/drive/MyDrive/Colab Notebooks/language project/M letter/murrinh-patha.gif")

M_lang_letters=lang_letter("musey","/content/drive/MyDrive/Colab Notebooks/language project/M letter/musey.gif")

M_lang_letters=lang_letter("musi","/content/drive/MyDrive/Colab Notebooks/language project/M letter/musi.gif")

M_lang_letters=lang_letter("muskogee","/content/drive/MyDrive/Colab Notebooks/language project/M letter/muskogee.gif")

M_lang_letters=lang_letter("mwaghavul","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mwaghavul.gif")

M_lang_letters=lang_letter("mwani","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mwani.gif")

M_lang_letters=lang_letter("mwotlap","/content/drive/MyDrive/Colab Notebooks/language project/M letter/mwotlap.gif")

M_lang_letters=lang_letter("Maisin","/content/drive/MyDrive/Colab Notebooks/language project/msc/Maisin.png")

M_lang_letters=lang_letter("Mandjak","/content/drive/MyDrive/Colab Notebooks/language project/msc/Mandjak.png")

M_lang_letters=lang_letter("maay","/content/drive/MyDrive/Colab Notebooks/language project/msc/maay.png")

M_lang_letters=lang_letter("Makaa","/content/drive/MyDrive/Colab Notebooks/language project/msc/makaa.png")

M_lang_letters=lang_letter("mayogo","/content/drive/MyDrive/Colab Notebooks/language project/msc/mayogo.png")