{afghanistan:{'Day': {0: 'Wednesday',
  1: 'Monday',
  2: 'Thursday',
  3: 'Saturday',
  4: 'Sunday',
  5: 'Monday',
  6: 'Friday',
  7: 'Monday',
  8: 'Wednesday',
  9: 'Thursday',
  10: 'Friday',
  11: 'Saturday',
  12: 'Tuesday',
  13: 'Saturday',
  14: 'Thursday',
  15: 'Wednesday'},
 'Date': {0: 'Feb 15',
  1: 'Mar 20',
  2: 'Mar 23',
  3: 'Apr 22',
  4: 'Apr 23',
  5: 'Apr 24',
  6: 'Apr 28',
  7: 'May 01',
  8: 'Jun 28',
  9: 'Jun 29',
  10: 'Jun 30',
  11: 'Jul 01',
  12: 'Aug 15',
  13: 'Aug 19',
  14: 'Aug 31',
  15: 'Sep 27'},
 'Holiday Name': {0: 'Liberation Day',
  1: 'Nowrooz',
  2: 'Ramadan',
  3: 'Eid al-Fitr',
  4: 'Eid al-Fitr Holiday',
  5: 'Eid al-Fitr Holiday',
  6: 'Mujahideen Victory Day',
  7: 'Labour Day',
  8: 'Day of Arafa',
  9: 'Eid Al Adha',
  10: 'Eid Al Adha Holiday',
  11: 'Eid Al Adha Holiday',
  12: 'Victory of the Islamic Emirate',
  13: 'Independence Day',
  14: 'Public Holiday',
  15: 'Eid Milad-un-Nabi'},
 'Type': {0: 'National Holiday',
  1: 'Not A Public Holiday',
  2: 'National Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'National Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'National Holiday',
  10: 'National Holiday',
  11: 'National Holiday',
  12: 'National Holiday',
  13: 'National Holiday',
  14: 'National Holiday',
  15: 'National Holiday'},
 'Comments': {0: "nan",
  1: 'Afghan New Year',
  2: 'Expected Start of Ramadan',
  3: 'End of Ramadan',
  4: "nan",
  5: "nan",
  6: "nan",
  7: "International Workers' Day",
  8: "nan",
  9: 'Feast of the Sacrifice',
  10: "nan",
  11: "nan",
  12: "nan",
  13: 'National Day',
  14: "nan",
  15: "nan"}},albania:{'Day': {0: 'Sunday',
  1: 'Monday',
  2: 'Tuesday',
  3: 'Tuesday',
  4: 'Wednesday',
  5: 'Sunday',
  6: 'Monday',
  7: 'Sunday',
  8: 'Monday',
  9: 'Friday',
  10: 'Monday',
  11: 'Wednesday',
  12: 'Tuesday',
  13: 'Tuesday',
  14: 'Wednesday',
  15: 'Friday',
  16: 'Monday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 02',
  2: 'Jan 03',
  3: 'Mar 14',
  4: 'Mar 22',
  5: 'Apr 09',
  6: 'Apr 10',
  7: 'Apr 16',
  8: 'Apr 17',
  9: 'Apr 21',
  10: 'May 01',
  11: 'Jun 28',
  12: 'Sep 05',
  13: 'Nov 28',
  14: 'Nov 29',
  15: 'Dec 08',
  16: 'Dec 25'},
 'Holiday Name': {0: "New Year's Day",
  1: "Day after New Year's Day (in lieu)",
  2: "New Year's Day (in lieu)",
  3: 'Summer Day',
  4: 'Nevruz',
  5: 'Easter (Catholic)',
  6: 'Easter Monday',
  7: 'Orthodox Easter Day',
  8: 'Orthodox Easter Monday',
  9: 'Eid al-Fitr',
  10: 'Labour Day',
  11: 'Eid Al Adha',
  12: 'Saint Teresa Canonisation Day',
  13: 'Independence Day',
  14: 'Liberation Day',
  15: 'Albanian National Youth Day',
  16: 'Christmas Day'},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'National Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'National Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'National Holiday',
  10: 'National Holiday',
  11: 'National Holiday',
  12: 'National Holiday',
  13: 'National Holiday',
  14: 'National Holiday',
  15: 'National Holiday',
  16: 'National Holiday'},
 'Comments': {0: "nan",
  1: "nan",
  2: "nan",
  3: "nan",
  4: 'Spring Festival',
  5: "nan",
  6: "nan",
  7: "nan",
  8: "nan",
  9: 'End of Ramadan',
  10: "International Workers' Day",
  11: 'Feast of the Sacrifice',
  12: "nan",
  13: "nan",
  14: "nan",
  15: "nan",
  16: "nan"}},algeria:{'Day': {0: 'Sunday',
  1: 'Thursday',
  2: 'Wednesday',
  3: 'Saturday',
  4: 'Monday',
  5: 'Thursday',
  6: 'Wednesday',
  7: 'Wednesday',
  8: 'Friday',
  9: 'Wednesday',
  10: 'Wednesday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 12',
  2: 'Feb 22',
  3: 'Apr 22',
  4: 'May 01',
  5: 'Jun 29',
  6: 'Jul 05',
  7: 'Jul 19',
  8: 'Jul 28',
  9: 'Sep 27',
  10: 'Nov 01'},
 'Holiday Name': {0: "New Year's Day",
  1: 'Yennayer',
  2: 'Day of Fraternity and Cohesion',
  3: 'Eid-ul-Fitr',
  4: 'Labour Day',
  5: 'Eid Al Adha',
  6: 'Independence Day',
  7: 'Awal Muharram',
  8: 'Ashura',
  9: 'Mawlid',
  10: 'Anniversary of the Revolution'},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'National Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'National Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'National Holiday',
  10: 'National Holiday'},
 'Comments': {0: "nan",
  1: 'Berber New Year',
  2: "nan",
  3: 'End of Ramadan',
  4: "International Workers' Day",
  5: 'Sacrifice Feast',
  6: "nan",
  7: 'Islamic New Year',
  8: '10th day of Muharram',
  9: 'Birthday of Prophet Muhammad',
  10: "nan"}},american-samoa:{'Day': {0: 'Sunday',
  1: 'Monday',
  2: 'Monday',
  3: 'Monday',
  4: 'Friday',
  5: 'Monday',
  6: 'Monday',
  7: 'Monday',
  8: 'Tuesday',
  9: 'Sunday',
  10: 'Monday',
  11: 'Monday',
  12: 'Sunday',
  13: 'Monday',
  14: 'Friday',
  15: 'Saturday',
  16: 'Thursday',
  17: 'Monday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 02',
  2: 'Jan 16',
  3: 'Feb 20',
  4: 'Apr 07',
  5: 'Apr 17',
  6: 'May 29',
  7: 'Jun 19',
  8: 'Jul 04',
  9: 'Jul 16',
  10: 'Jul 17',
  11: 'Sep 04',
  12: 'Oct 08',
  13: 'Oct 09',
  14: 'Nov 10',
  15: 'Nov 11',
  16: 'Nov 23',
  17: 'Dec 25'},
 'Holiday Name': {0: "New Year's Day",
  1: "New Year's Day (in lieu)",
  2: 'Martin Luther King Jr. Day',
  3: "President's Day",
  4: 'Good Friday',
  5: 'American Samoa Flag Day',
  6: 'Memorial Day',
  7: 'Juneteenth',
  8: 'US Independence Day',
  9: 'Manu’a Cession Day',
  10: 'Manu’a Cession Day (in lieu)',
  11: 'Labor Day',
  12: 'White Sunday',
  13: 'Columbus Day',
  14: 'Veterans Day (in lieu)',
  15: 'Veterans Day',
  16: 'Thanksgiving',
  17: 'Christmas Day'},
 'Type': {0: 'Public Holiday',
  1: 'Public Holiday',
  2: 'Public Holiday',
  3: 'Public Holiday',
  4: 'Public Holiday',
  5: 'Public Holiday',
  6: 'Public Holiday',
  7: 'Public Holiday',
  8: 'Public Holiday',
  9: 'Public Holiday',
  10: 'Public Holiday',
  11: 'Public Holiday',
  12: 'Public Holiday',
  13: 'Public Holiday',
  14: 'Public Holiday',
  15: 'Public Holiday',
  16: 'Public Holiday',
  17: 'Public Holiday'},
 'Comments': {0: 'Federal Holiday',
  1: 'Federal Holiday',
  2: '3rd Monday in January',
  3: '3rd Monday in February',
  4: "nan",
  5: "nan",
  6: 'Last Monday in May',
  7: 'Emancipation Day',
  8: "nan",
  9: "nan",
  10: "nan",
  11: '1st Monday in September',
  12: 'Second Sunday in October',
  13: '2nd Monday in October',
  14: "nan",
  15: "nan",
  16: '4th Thursday in November',
  17: "nan"}},andorra:{'Day': {0: 'Sunday',
  1: 'Friday',
  2: 'Tuesday',
  3: 'Tuesday',
  4: 'Friday',
  5: 'Monday',
  6: 'Monday',
  7: 'Monday',
  8: 'Tuesday',
  9: 'Friday',
  10: 'Wednesday',
  11: 'Friday',
  12: 'Monday',
  13: 'Tuesday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 06',
  2: 'Feb 21',
  3: 'Mar 14',
  4: 'Apr 07',
  5: 'Apr 10',
  6: 'May 01',
  7: 'May 29',
  8: 'Aug 15',
  9: 'Sep 08',
  10: 'Nov 01',
  11: 'Dec 08',
  12: 'Dec 25',
  13: 'Dec 26'},
 'Holiday Name': {0: "New Year's Day",
  1: 'Epiphany',
  2: 'Carnival',
  3: 'Constitution Day',
  4: 'Good Friday',
  5: 'Easter Monday',
  6: 'Labour Day',
  7: 'Whit Monday',
  8: 'Assumption Day',
  9: 'Meritxell Day',
  10: "All Saints' Day",
  11: 'Immaculate Conception Day',
  12: 'Christmas Day',
  13: "St. Stephen's Day"},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'National Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'National Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'National Holiday',
  10: 'National Holiday',
  11: 'National Holiday',
  12: 'National Holiday',
  13: 'National Holiday'},
 'Comments': {0: "nan",
  1: "nan",
  2: 'Tuesday before Ash Wednesday',
  3: "nan",
  4: "nan",
  5: "nan",
  6: "International Workers' Day",
  7: '7th Monday after Easter',
  8: "nan",
  9: 'National Day',
  10: "nan",
  11: "nan",
  12: "nan",
  13: "nan"}},angola:{'Day': {0: 'Sunday',
  1: 'Saturday',
  2: 'Tuesday',
  3: 'Wednesday',
  4: 'Tuesday',
  5: 'Friday',
  6: 'Sunday',
  7: 'Monday',
  8: 'Sunday',
  9: 'Thursday',
  10: 'Saturday',
  11: 'Monday'},
 'Date': {0: 'Jan 01',
  1: 'Feb 04',
  2: 'Feb 21',
  3: 'Mar 08',
  4: 'Apr 04',
  5: 'Apr 07',
  6: 'Apr 09',
  7: 'May 01',
  8: 'Sep 17',
  9: 'Nov 02',
  10: 'Nov 11',
  11: 'Dec 25'},
 'Holiday Name': {0: "New Year's Day",
  1: 'Liberation Day',
  2: 'Carnival Tuesday',
  3: "Women's Day",
  4: 'Peace Day',
  5: 'Good Friday',
  6: 'Easter Sunday',
  7: 'Labour Day',
  8: "National Heroes' Day",
  9: "All Souls' Day",
  10: 'Independence Day',
  11: 'Christmas Day and Family Day'},
 'Comments': {0: "nan",
  1: "Colonial Repression Martyrs' Day",
  2: 'Celebrated Tuesday before Ash Wednesday',
  3: "nan",
  4: 'Day of Peace and Reconciliation',
  5: "nan",
  6: "nan",
  7: "International Workers' Day",
  8: "nan",
  9: 'Memorial Day',
  10: 'National Day',
  11: "nan"}},anguilla:{'Day': {0: 'Sunday',
  1: 'Thursday',
  2: 'Friday',
  3: 'Monday',
  4: 'Monday',
  5: 'Monday',
  6: 'Tuesday',
  7: 'Monday',
  8: 'Monday',
  9: 'Thursday',
  10: 'Friday',
  11: 'Tuesday',
  12: 'Monday',
  13: 'Tuesday'},
 'Date': {0: 'Jan 01',
  1: 'Mar 02',
  2: 'Apr 07',
  3: 'Apr 10',
  4: 'May 01',
  5: 'May 29',
  6: 'May 30',
  7: 'Jun 12',
  8: 'Aug 07',
  9: 'Aug 10',
  10: 'Aug 11',
  11: 'Dec 19',
  12: 'Dec 25',
  13: 'Dec 26'},
 'Holiday Name': {0: "New Year's Day",
  1: 'James Ronald Webster Day',
  2: 'Good Friday',
  3: 'Easter Monday',
  4: 'Labour Day (in lieu)',
  5: 'Whit Monday',
  6: 'Anguilla Day',
  7: 'Celebration of the Birthday of His Majesty the King',
  8: 'August Monday',
  9: 'August Thursday',
  10: 'Constitution Day',
  11: 'National Heroes and Heroines Day',
  12: 'Christmas Day',
  13: 'Boxing Day'},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'National Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'National Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'National Holiday',
  10: 'National Holiday',
  11: 'National Holiday',
  12: 'National Holiday',
  13: 'National Holiday'},
 'Comments': {0: "nan",
  1: "nan",
  2: "nan",
  3: "nan",
  4: "International Workers' Day",
  5: '7th Monday after Easter',
  6: 'National Day',
  7: "nan",
  8: 'First Monday of August',
  9: 'Thursday after first Monday of August',
  10: "nan",
  11: "nan",
  12: "nan",
  13: "nan"}},antigua_barbuda:{'Day': {0: 'Sunday',
  1: 'Monday',
  2: 'Thursday',
  3: 'Friday',
  4: 'Monday',
  5: 'Monday',
  6: 'Monday',
  7: 'Tuesday',
  8: 'Monday',
  9: 'Tuesday',
  10: 'Wednesday',
  11: 'Saturday',
  12: 'Monday',
  13: 'Tuesday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 02',
  2: 'Jan 19',
  3: 'Apr 07',
  4: 'Apr 10',
  5: 'May 01',
  6: 'May 29',
  7: 'Jul 04',
  8: 'Aug 07',
  9: 'Aug 08',
  10: 'Nov 01',
  11: 'Dec 09',
  12: 'Dec 25',
  13: 'Dec 26'},
 'Holiday Name': {0: "New Year's Day",
  1: "New Year's Day (in lieu)",
  2: 'Public Holiday',
  3: 'Good Friday',
  4: 'Easter Monday',
  5: 'Labour Day',
  6: 'Whit Monday',
  7: 'Caricom Day',
  8: 'Carnival Monday',
  9: 'Carnival Tuesday',
  10: 'Independence Day',
  11: 'V.C. Bird Day',
  12: 'Christmas Day',
  13: 'Boxing Day'},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'National Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'National Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'National Holiday',
  10: 'National Holiday',
  11: 'National Holiday',
  12: 'National Holiday',
  13: 'National Holiday'},
 'Comments': {0: "nan",
  1: "nan",
  2: "nan",
  3: "nan",
  4: "nan",
  5: 'First Monday in May',
  6: '7th Monday after Easter',
  7: '1st Monday in July',
  8: 'First Monday in August',
  9: 'Tuesday after first Monday in August',
  10: 'National Day',
  11: "nan",
  12: "nan",
  13: "nan"}},argentina:{'Day': {0: 'Sunday',
  1: 'Monday',
  2: 'Tuesday',
  3: 'Friday',
  4: 'Sunday',
  5: 'Thursday',
  6: 'Friday',
  7: 'Monday',
  8: 'Thursday',
  9: 'Friday',
  10: 'Saturday',
  11: 'Sunday',
  12: 'Monday',
  13: 'Tuesday',
  14: 'Tuesday',
  15: 'Sunday',
  16: 'Monday',
  17: 'Friday',
  18: 'Sunday',
  19: 'Monday',
  20: 'Monday',
  21: 'Friday',
  22: 'Monday'},
 'Date': {0: 'Jan 01',
  1: 'Feb 20',
  2: 'Feb 21',
  3: 'Mar 24',
  4: 'Apr 02',
  5: 'Apr 06',
  6: 'Apr 07',
  7: 'May 01',
  8: 'May 25',
  9: 'May 26',
  10: 'Jun 17',
  11: 'Jun 18',
  12: 'Jun 19',
  13: 'Jun 20',
  14: 'Jun 27',
  15: 'Jul 09',
  16: 'Aug 21',
  17: 'Oct 13',
  18: 'Oct 15',
  19: 'Oct 16',
  20: 'Nov 20',
  21: 'Dec 08',
  22: 'Dec 25'},
 'Holiday Name': {0: "New Year's Day",
  1: 'Carnival Monday',
  2: 'Carnival Tuesday',
  3: 'Truth and Justice Memorial Day',
  4: 'Malvinas Day',
  5: 'Maundy Thursday',
  6: 'Good Friday',
  7: 'Labour Day',
  8: 'May Day Revolution',
  9: 'May Day Revolution (bridge day)',
  10: 'Martin Miguel de Guemes Day',
  11: "Father's Day",
  12: 'National Flag Day (bridge day)',
  13: 'National Flag Day',
  14: 'Day of the State Worker',
  15: 'Independence Day',
  16: "San Martin's Day",
  17: 'Public Holiday Holiday',
  18: "Mother's Day",
  19: 'Day of respect for cultural diversity',
  20: 'Day of National Sovereignty',
  21: 'Immaculate Conception Day',
  22: 'Christmas Day'},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'National Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'Not A Public Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'National Holiday',
  10: 'National Holiday',
  11: 'Not A Public Holiday',
  12: 'National Holiday',
  13: 'National Holiday',
  14: 'Government Holiday',
  15: 'National Holiday',
  16: 'National Holiday',
  17: 'National Holiday',
  18: 'Not A Public Holiday',
  19: 'National Holiday',
  20: 'National Holiday',
  21: 'National Holiday',
  22: 'National Holiday'},
 'Comments': {0: "nan",
  1: 'Monday before Ash Wednesday',
  2: 'Tuesday before Ash Wednesday',
  3: "nan",
  4: "Veteran's Day",
  5: 'International Catholic holiday (optional)',
  6: "nan",
  7: "International Workers' Day",
  8: "nan",
  9: "nan",
  10: 'Celebrated since 2016',
  11: '3rd Sunday in June. Not a public holiday',
  12: "nan",
  13: "nan",
  14: 'Public sector only',
  15: "nan",
  16: 'Third Monday in August',
  17: "nan",
  18: '3rd Sunday in October',
  19: "nan",
  20: 'Fourth Monday in November',
  21: 'Also known as Virgins Day',
  22: "nan"}},armenia:{'Day': {0: 'Sunday',
  1: 'Monday',
  2: 'Friday',
  3: 'Saturday',
  4: 'Wednesday',
  5: 'Monday',
  6: 'Monday',
  7: 'Monday',
  8: 'Tuesday',
  9: 'Sunday',
  10: 'Wednesday',
  11: 'Monday',
  12: 'Thursday',
  13: 'Sunday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 02',
  2: 'Jan 06',
  3: 'Jan 28',
  4: 'Mar 08',
  5: 'Apr 10',
  6: 'Apr 24',
  7: 'May 01',
  8: 'May 09',
  9: 'May 28',
  10: 'Jul 05',
  11: 'Sep 18',
  12: 'Sep 21',
  13: 'Dec 31'},
 'Holiday Name': {0: "New Year's Day",
  1: "New Year's Day (in lieu)",
  2: 'Christmas Day',
  3: 'National Army Day',
  4: "Women's Day",
  5: 'Easter Monday',
  6: 'Genocide Memorial Day',
  7: 'Labor Day',
  8: 'Victory Day',
  9: 'Day of the First Republic',
  10: 'Constitution Day',
  11: 'Exaltation of the Holy Cross',
  12: 'Independence Day',
  13: "New Year's Eve"},
 'Comments': {0: "nan",
  1: "nan",
  2: "nan",
  3: "nan",
  4: "nan",
  5: 'Merelots',
  6: "nan",
  7: "International Workers' Day",
  8: "nan",
  9: 'National Day',
  10: "nan",
  11: 'Merelots',
  12: "nan",
  13: "nan"}},aruba:{'Day': {0: 'Sunday',
  1: 'Wednesday',
  2: 'Monday',
  3: 'Saturday',
  4: 'Friday',
  5: 'Monday',
  6: 'Thursday',
  7: 'Monday',
  8: 'Thursday',
  9: 'Monday',
  10: 'Tuesday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 25',
  2: 'Feb 20',
  3: 'Mar 18',
  4: 'Apr 07',
  5: 'Apr 10',
  6: 'Apr 27',
  7: 'May 01',
  8: 'May 18',
  9: 'Dec 25',
  10: 'Dec 26'},
 'Holiday Name': {0: "New Year's Day",
  1: 'Betico Croes Day',
  2: 'Carnival Monday',
  3: 'National Anthem and Flag Day',
  4: 'Good Friday',
  5: 'Easter Monday',
  6: "King's Birthday",
  7: 'Labour Day',
  8: 'Ascension Day',
  9: 'Christmas Day',
  10: 'Boxing Day'},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'National Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'National Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'National Holiday',
  10: 'National Holiday'},
 'Comments': {0: "nan",
  1: "nan",
  2: 'Monday before Ash Wednesday',
  3: 'National Day',
  4: "nan",
  5: "nan",
  6: 'National Day',
  7: "International Workers' Day",
  8: '39 days after Easter Sunday',
  9: "nan",
  10: "nan"}},australia:{'Day': {0: 'Sunday',
  1: 'Monday',
  2: 'Thursday',
  3: 'Monday',
  4: 'Monday',
  5: 'Monday',
  6: 'Monday',
  7: 'Monday',
  8: 'Friday',
  9: 'Saturday',
  10: 'Sunday',
  11: 'Monday',
  12: 'Tuesday',
  13: 'Tuesday',
  14: 'Monday',
  15: 'Sunday',
  16: 'Monday',
  17: 'Monday',
  18: 'Monday',
  19: 'Monday',
  20: 'Monday',
  21: 'Wednesday',
  22: 'Sunday',
  23: 'Monday',
  24: 'Friday',
  25: 'Monday',
  26: 'Monday',
  27: 'Monday',
  28: 'Tuesday',
  29: 'Sunday',
  30: 'Sunday',
  31: 'Sunday',
  32: 'Monday',
  33: 'Tuesday',
  34: 'Tuesday',
  35: 'Sunday',
  36: 'Sunday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 02',
  2: 'Jan 26',
  3: 'Feb 13',
  4: 'Mar 06',
  5: 'Mar 13',
  6: 'Mar 13',
  7: 'Mar 13',
  8: 'Apr 07',
  9: 'Apr 08',
  10: 'Apr 09',
  11: 'Apr 10',
  12: 'Apr 11',
  13: 'Apr 25',
  14: 'May 01',
  15: 'May 14',
  16: 'May 29',
  17: 'Jun 05',
  18: 'Jun 12',
  19: 'Aug 07',
  20: 'Aug 07',
  21: 'Aug 16',
  22: 'Sep 03',
  23: 'Sep 25',
  24: 'Sep 29',
  25: 'Oct 02',
  26: 'Oct 02',
  27: 'Nov 06',
  28: 'Nov 07',
  29: 'Dec 24',
  30: 'Dec 24',
  31: 'Dec 24',
  32: 'Dec 25',
  33: 'Dec 26',
  34: 'Dec 26',
  35: 'Dec 31',
  36: 'Dec 31'},
 'Holiday Name': {0: "New Year's Day",
  1: "New Year's Day Holiday",
  2: 'Australia Day',
  3: 'Royal Hobart Regatta',
  4: 'Labour Day',
  5: 'Adelaide Cup',
  6: 'Labour Day',
  7: 'Canberra Day',
  8: 'Good Friday',
  9: 'Holy Saturday',
  10: 'Easter Sunday',
  11: 'Easter Monday',
  12: 'Easter Tuesday',
  13: 'Anzac Day',
  14: 'Labour Day',
  15: "Mother's Day",
  16: 'Reconciliation Day',
  17: 'Western Australia Day',
  18: "King's Birthday",
  19: 'Bank Holiday',
  20: 'Picnic Day',
  21: "Ekka People's Day",
  22: "Father's Day",
  23: "King's Birthday",
  24: 'Grand Final Eve',
  25: 'Labour Day',
  26: "Kings's Birthday",
  27: 'Recreation Day',
  28: 'Melbourne Cup Day',
  29: 'Christmas Eve',
  30: 'Christmas Eve',
  31: 'Christmas Eve',
  32: 'Christmas Day',
  33: 'Boxing Day',
  34: 'Proclamation Day',
  35: "New Year's Eve",
  36: "New Year's Eve"},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'National Holiday',
  3: 'Regional Holiday',
  4: 'Regional Holiday',
  5: 'Regional Holiday',
  6: 'Regional Holiday',
  7: 'Regional Holiday',
  8: 'National Holiday',
  9: 'Regional Holiday',
  10: 'Regional Holiday',
  11: 'National Holiday',
  12: 'Government Holiday',
  13: 'National Holiday',
  14: 'Regional Holiday',
  15: 'Not A Public Holiday',
  16: 'Regional Holiday',
  17: 'Regional Holiday',
  18: 'Regional Holiday',
  19: 'Not A Public Holiday',
  20: 'Regional Holiday',
  21: 'Regional Holiday',
  22: 'Not A Public Holiday',
  23: 'Regional Holiday',
  24: 'Regional Holiday',
  25: 'Regional Holiday',
  26: 'Regional Holiday',
  27: 'Regional Holiday',
  28: 'Regional Holiday',
  29: 'Regional Holiday',
  30: 'Regional Holiday',
  31: 'Regional Holiday',
  32: 'National Holiday',
  33: 'Regional Holiday',
  34: 'Regional Holiday',
  35: 'Regional Holiday',
  36: 'Regional Holiday'},
 'Comments': {0: "nan",
  1: "nan",
  2: "nan",
  3: 'Tasmania Regional',
  4: 'WA',
  5: '2nd Monday in March. SA Only',
  6: 'VIC, TAS',
  7: 'ACT. Second Monday in March',
  8: "nan",
  9: 'Except TAS, WA',
  10: 'ACT, NSW, QLD, VIC, WA',
  11: 'Monday after Easter Sunday',
  12: 'Tasmania. Government only',
  13: "nan",
  14: 'QLD, NT',
  15: '2nd Sunday in May. Not a public holiday',
  16: 'ACT',
  17: 'First Monday in June. WA only',
  18: '2nd Monday in June. except QLD, WA',
  19: 'New South Wales. Banks only',
  20: '1st Monday in August. NT Only',
  21: 'Royal Queensland Show. Brisbane',
  22: '1st Sunday in September. Not a public holiday',
  23: 'Last Monday in September. WA Only',
  24: 'Victoria. Probable Date',
  25: 'NSW, ACT, SA',
  26: '1st Monday in October. QLD',
  27: 'Tasmania regional',
  28: '1st Tuesday in November. VIC Only',
  29: 'South Australia. From 7pm - midnight',
  30: 'Queensland. From 6pm - midnight',
  31: 'Northern Territory. From 7pm - midnight',
  32: "nan",
  33: 'Except South Australia',
  34: 'South Australia',
  35: 'South Australia. From 7pm - midnight',
  36: 'Northern Territory. From 7pm - midnight'}},austria:{'Day': {0: 'Sunday',
  1: 'Friday',
  2: 'Friday',
  3: 'Monday',
  4: 'Monday',
  5: 'Sunday',
  6: 'Thursday',
  7: 'Monday',
  8: 'Thursday',
  9: 'Sunday',
  10: 'Tuesday',
  11: 'Sunday',
  12: 'Thursday',
  13: 'Wednesday',
  14: 'Wednesday',
  15: 'Friday',
  16: 'Monday',
  17: 'Tuesday',
  18: 'Sunday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 06',
  2: 'Apr 07',
  3: 'Apr 10',
  4: 'May 01',
  5: 'May 14',
  6: 'May 18',
  7: 'May 29',
  8: 'Jun 08',
  9: 'Jun 11',
  10: 'Aug 15',
  11: 'Sep 24',
  12: 'Oct 26',
  13: 'Nov 01',
  14: 'Nov 15',
  15: 'Dec 08',
  16: 'Dec 25',
  17: 'Dec 26',
  18: 'Dec 31'},
 'Holiday Name': {0: "New Year's Day",
  1: 'Epiphany',
  2: 'Good Friday',
  3: 'Easter Monday',
  4: 'Labour Day',
  5: "Mother's Day",
  6: 'Ascension Day',
  7: 'Whit Monday',
  8: 'Corpus Christi',
  9: "Father's Day",
  10: 'Assumption Day',
  11: "Saint Rupert's Day",
  12: 'National Day',
  13: "All Saints' Day",
  14: "Saint Leopold's Day",
  15: 'Immaculate Conception Day',
  16: 'Christmas Day',
  17: "St. Stephen's Day",
  18: "New Year's Eve"},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'Not A Public Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'Not A Public Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'Not A Public Holiday',
  10: 'National Holiday',
  11: 'Regional Holiday',
  12: 'National Holiday',
  13: 'National Holiday',
  14: 'Regional Holiday',
  15: 'National Holiday',
  16: 'National Holiday',
  17: 'National Holiday',
  18: 'Not A Public Holiday'},
 'Comments': {0: "nan",
  1: "nan",
  2: 'de facto',
  3: "nan",
  4: "International Workers' Day",
  5: '2nd Sunday in May. Not a public holiday',
  6: '39 days after Easter Sunday',
  7: '7th Monday after Easter',
  8: 'Second Thursday after Whitsun',
  9: '2nd Sunday in June. Not a public holiday',
  10: "nan",
  11: 'Salzburg',
  12: "nan",
  13: "nan",
  14: 'Vienna',
  15: "nan",
  16: "nan",
  17: "nan",
  18: 'de facto'}},azerbaijan:{'Day': {0: 'Sunday',
  1: 'Monday',
  2: 'Tuesday',
  3: 'Wednesday',
  4: 'Friday',
  5: 'Wednesday',
  6: 'Monday',
  7: 'Tuesday',
  8: 'Wednesday',
  9: 'Thursday',
  10: 'Friday',
  11: 'Friday',
  12: 'Saturday',
  13: 'Sunday',
  14: 'Monday',
  15: 'Tuesday',
  16: 'Monday',
  17: 'Thursday',
  18: 'Monday',
  19: 'Thursday',
  20: 'Friday',
  21: 'Wednesday',
  22: 'Wednesday',
  23: 'Thursday',
  24: 'Sunday'},
 'Date': {0: 'Jan 01',
  1: 'Jan 02',
  2: 'Jan 03',
  3: 'Jan 04',
  4: 'Jan 20',
  5: 'Mar 08',
  6: 'Mar 20',
  7: 'Mar 21',
  8: 'Mar 22',
  9: 'Mar 23',
  10: 'Mar 24',
  11: 'Apr 21',
  12: 'Apr 22',
  13: 'Apr 23',
  14: 'Apr 24',
  15: 'May 09',
  16: 'May 29',
  17: 'Jun 15',
  18: 'Jun 26',
  19: 'Jun 29',
  20: 'Jun 30',
  21: 'Oct 18',
  22: 'Nov 08',
  23: 'Nov 09',
  24: 'Dec 31'},
 'Holiday Name': {0: "New Year's Day",
  1: "New Year's Holiday",
  2: "New Year's Holiday",
  3: "New Year's Holiday",
  4: "Martyrs' Day",
  5: "Women's Day",
  6: 'Novruz',
  7: 'Novruz Holiday',
  8: 'Novruz Holiday',
  9: 'Novruz Holiday',
  10: 'Novruz Holiday',
  11: 'Ramazan Bayrami',
  12: 'Ramazan Bayrami Holiday',
  13: 'Ramazan Bayrami Holiday',
  14: 'Ramazan Bayrami Holiday',
  15: 'Victory Day',
  16: 'Republic Day (in lieu)',
  17: 'National Salvation Day',
  18: 'Armed Forces Day',
  19: 'Gurban Bayrami',
  20: 'Gurban Bayrami Holiday',
  21: 'Independence Day',
  22: 'Azerbaijani Victory Day',
  23: 'Flag Day',
  24: 'World Azerbaijanis Solidarity Day'},
 'Type': {0: 'National Holiday',
  1: 'National Holiday',
  2: 'National Holiday',
  3: 'National Holiday',
  4: 'National Holiday',
  5: 'National Holiday',
  6: 'National Holiday',
  7: 'National Holiday',
  8: 'National Holiday',
  9: 'National Holiday',
  10: 'National Holiday',
  11: 'National Holiday',
  12: 'National Holiday',
  13: 'National Holiday',
  14: 'National Holiday',
  15: 'National Holiday',
  16: 'National Holiday',
  17: 'National Holiday',
  18: 'National Holiday',
  19: 'National Holiday',
  20: 'National Holiday',
  21: 'Not A Public Holiday',
  22: 'National Holiday',
  23: 'National Holiday',
  24: 'National Holiday'},
 'Comments': {0: "nan",
  1: "nan",
  2: "nan",
  3: "nan",
  4: "nan",
  5: "nan",
  6: 'Spring Festival. Persian New Year.',
  7: "nan",
  8: "nan",
  9: "nan",
  10: "nan",
  11: 'Eid Al-Fitr',
  12: "nan",
  13: "nan",
  14: "nan",
  15: "nan",
  16: 'National Day',
  17: '15 June or following Monday',
  18: "nan",
  19: 'Feast of the Sacrifice',
  20: "nan",
  21: 'Not a non-working day',
  22: "nan",
  23: "nan",
  24: "nan"}}}